source 'https://rubygems.org/'

gem 'embulk'
gem 'embulk-output-elasticsearch'
gem 'embulk-output-opensearch'

source 'https://rubygems.pkg.github.com/calorie' do
  gem 'embulk-filter-speedometer'
end
