version: '3.1'
services:
  opensearch:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    expose:
      - 9200
    ports:
      - "9200:9200"
  java:
    image: eclipse-temurin:11
    volumes:
      - .:/embulk
    working_dir: /embulk

volumes:
  opensearch-data1:
