version: '3.9'
services:
  opensearch:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-node-bench
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node-bench
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch-node-bench
    environment:
      - cluster.name=elasticsearch-cluster
      - node.name=elasticsearch-node-bench
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
  embulk:
    build:
      context: ./embulk
      args:
        - PACKAGE_USER
        - PACKAGE_TOKEN
    volumes:
      - .:/bench
    working_dir: /embulk
