name: Check

on:
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run opensearch container
        run: docker compose up -d opensearch

      - name: Testing
        run: docker compose run --rm java ./gradlew check --console rich --info

      - name: Check building
        run: docker compose run --rm java ./gradlew gem --console rich --info

      - name: Publish
        run: |
          mkdir ~/.gem
          echo "---" > ~/.gem/credentials
          echo ":github: Bearer ${{ secrets.PACKAGE_TOKEN }}" >> ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          find ./build/gems -name 'embulk-output-opensearch-*.gem' -maxdepth 1 -print0 | xargs -0 gem push --key github --host 'https://rubygems.pkg.github.com/calorie'
