name: Check

on:
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PACKAGE_USERNAME: ${{ secrets.PACKAGE_USERNAME }}
      PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Run opensearch container
        run: docker compose up -d opensearch

      - name: Check building
        run: docker compose run --rm java ./gradlew gem --console rich --info
