name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build gem
        run: docker compose run --rm java ./gradlew gem
        env:
          PACKAGE_USERNAME: ${{ secrets.PACKAGE_USERNAME }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Publish
        run: |
          mkdir ~/.gem
          echo "---" > ~/.gem/credentials
          echo ":rubygems_api_key: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}" >> ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          find ./build/gems -name 'embulk-output-opensearch-*.gem' -maxdepth 1 -print0 | xargs -0 gem push
